name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH Deploy
        env:
          PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          HOST_NAME: "${{ secrets.SSH_HOST }}"
          USER_NAME: "${{ secrets.USER_NAME }}"
          PROJECT_PATH: "${{ secrets.PROJECT_PATH }}"
          GIT_REPO: "${{ secrets.GIT_REPO }}"
        run: |
          mkdir -p ~/.ssh

          echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh-keyscan -H "$HOST_NAME" >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key "$USER_NAME@$HOST_NAME" <<EOF
            # If the project path exists but is NOT a git repository, delete it
            if [ -d "$PROJECT_PATH" ] && [ ! -d "$PROJECT_PATH/.git" ]; then
              echo "Directory exists but is not a Git repo. Deleting..."
              rm -rf "$PROJECT_PATH"
            fi

            # If the project path does NOT exist, clone it
            if [ ! -d "$PROJECT_PATH" ]; then
              mkdir -p "$(dirname "$PROJECT_PATH")"
              git clone "$GIT_REPO" "$PROJECT_PATH"
            fi

            cd "$PROJECT_PATH"
            git fetch --all
            git reset --hard origin/main
            git pull origin main
          EOF